### ISSUE TITLE
Noninteractive image builds

### ISSUE THREAD

**Issue by vaonet-jks** [tobetter/odroid-stamper#6]
- To keep installations from prompting users (and pausing the build), insert at ./odroid-stamper/fixups/S20-install-packages:5
~~~
locale-gen en_US.UTF-8

export DEBIAN_FRONTEND
DEBIAN_FRONTEND=noninteractive

~~~

**Comment by tobetter** [comment]
Applied, thanks.

https://github.com/tobetter/odroid-stamper/commit/d4c7b5768485e9c1d9d0a84c10666743840e227f
