### ISSUE TITLE
Copy overlay before running fixups

### ISSUE THREAD

**Issue by vaonet-jks** [tobetter/odroid-stamper#8]
Copy overlay files before running fixups. This is to help install files that are not part of a package. Source files are copied to a temp directory as part of overlay and a fixup can install them, create symbolic links, etc. Temp directory is deleted by fixup once done.

**Comment by tobetter** [comment]
Files in overlay/ directory are copied prior to run the script in fixup/ already.
https://github.com/tobetter/odroid-stamper/blob/master/functions#L335
https://github.com/tobetter/odroid-stamper/blob/master/functions#L419

Can you please check them again?

**Comment by vaonet-jks** [comment]
You are correct! I am sorry.

**Comment by tobetter** [comment]
So...let me close this since you confirmed. :)
